name: Blocksy
version: "2.0.1"
main: it.blocksy.Blocksy
authors: [Ph1llyOn_]
description: Blocksy Vote Plugin - Bridge tra Sito e Votifier
softdepend: [Votifier, NuVotifier]
commands:
  blocksy:
    description: Comando principale di Blocksy
    permission: blocksy.admin
    usage: /blocksy reload
permissions:
  blocksy.admin:
    description: Permette di gestire il plugin Blocksy
    default: op
